# 权限系统配置文件
# 定义基础权限结构和分组

# 权限分组配置
permission_groups:
  # 用户管理权限组
  user_management:
    name: "用户管理"
    description: "用户相关的权限"
    permissions:
      - code: "user:create"
        name: "创建用户"
        description: "创建新用户账号"
        resource: "user"
        action: "create"
      - code: "user:read"
        name: "查看用户"
        description: "查看用户信息和列表"
        resource: "user"
        action: "read"
      - code: "user:update"
        name: "更新用户"
        description: "更新用户信息"
        resource: "user"
        action: "update"
      - code: "user:delete"
        name: "删除用户"
        description: "删除用户账号"
        resource: "user"
        action: "delete"
      - code: "user:profile"
        name: "用户档案"
        description: "查看和编辑用户档案"
        resource: "user"
        action: "profile"

  # 角色管理权限组
  role_management:
    name: "角色管理"
    description: "角色相关的权限"
    permissions:
      - code: "role:create"
        name: "创建角色"
        description: "创建新角色"
        resource: "role"
        action: "create"
      - code: "role:read"
        name: "查看角色"
        description: "查看角色信息和列表"
        resource: "role"
        action: "read"
      - code: "role:update"
        name: "更新角色"
        description: "更新角色信息"
        resource: "role"
        action: "update"
      - code: "role:delete"
        name: "删除角色"
        description: "删除角色"
        resource: "role"
        action: "delete"
      - code: "role:assign"
        name: "分配角色"
        description: "给用户分配角色"
        resource: "role"
        action: "assign"

  # 权限管理权限组
  permission_management:
    name: "权限管理"
    description: "权限相关的权限"
    permissions:
      - code: "permission:create"
        name: "创建权限"
        description: "创建新权限"
        resource: "permission"
        action: "create"
      - code: "permission:read"
        name: "查看权限"
        description: "查看权限信息和列表"
        resource: "permission"
        action: "read"
      - code: "permission:update"
        name: "更新权限"
        description: "更新权限信息"
        resource: "permission"
        action: "update"
      - code: "permission:delete"
        name: "删除权限"
        description: "删除权限"
        resource: "permission"
        action: "delete"
      - code: "permission:assign"
        name: "分配权限"
        description: "给角色或用户分配权限"
        resource: "permission"
        action: "assign"

  # 菜单管理权限组
  menu_management:
    name: "菜单管理"
    description: "菜单相关的权限"
    permissions:
      - code: "menu:create"
        name: "创建菜单"
        description: "创建新菜单"
        resource: "menu"
        action: "create"
      - code: "menu:read"
        name: "查看菜单"
        description: "查看菜单信息和列表"
        resource: "menu"
        action: "read"
      - code: "menu:update"
        name: "更新菜单"
        description: "更新菜单信息"
        resource: "menu"
        action: "update"
      - code: "menu:delete"
        name: "删除菜单"
        description: "删除菜单"
        resource: "menu"
        action: "delete"

  # 系统配置权限组
  system_management:
    name: "系统管理"
    description: "系统相关的权限"
    permissions:
      - code: "system:config"
        name: "系统配置"
        description: "管理系统配置"
        resource: "system"
        action: "config"
      - code: "system:monitor"
        name: "系统监控"
        description: "查看系统监控信息"
        resource: "system"
        action: "monitor"
      - code: "system:log"
        name: "系统日志"
        description: "查看系统日志"
        resource: "system"
        action: "log"

  # 日志管理权限组
  log_management:
    name: "日志管理"
    description: "日志相关的权限"
    permissions:
      - code: "log:operation:read"
        name: "查看操作日志"
        description: "查看操作日志"
        resource: "log"
        action: "operation:read"
      - code: "log:login:read"
        name: "查看登录日志"
        description: "查看登录日志"
        resource: "log"
        action: "login:read"
      - code: "log:export"
        name: "导出日志"
        description: "导出日志数据"
        resource: "log"
        action: "export"

# 默认角色配置
default_roles:
  # 超级管理员角色
  admin:
    name: "超级管理员"
    description: "拥有系统所有权限"
    permission_groups: ["*"] # 通配符表示所有权限组
    permissions: [] # 由于是超级管理员，通过超级用户标识获得所有权限

  # 管理员角色
  manager:
    name: "管理员"
    description: "业务管理员，拥有大部分管理权限"
    permission_groups:
      - "user_management"
      - "role_management"
      - "menu_management"
      - "log_management"
    permissions:
      - "permission:read"
      - "system:monitor"

  # 普通用户角色
  user:
    name: "普通用户"
    description: "基础用户权限"
    permission_groups: []
    permissions:
      - "user:read"
      - "user:profile"
      - "menu:read"

# 权限继承配置
permission_inheritance:
  # 定义权限的层级关系
  hierarchies:
    - parent: "user:update"
      children: ["user:read"]
    - parent: "user:delete"
      children: ["user:read"]
    - parent: "role:assign"
      children: ["role:read", "user:read"]
    - parent: "permission:assign"
      children: ["permission:read", "role:read", "user:read"]

# 环境特定配置
environments:
  development:
    # 开发环境特殊权限
    additional_permissions:
      - code: "dev:debug"
        name: "调试权限"
        description: "开发环境调试权限"
        resource: "dev"
        action: "debug"

  production:
    # 生产环境禁用的权限
    disabled_permissions:
      - "dev:debug"

# 权限验证配置
validation:
  # 权限码格式验证
  permission_code_pattern: "^[a-z_]+:[a-z_:]+$"

  # 资源名称验证
  resource_name_pattern: "^[a-z_]+$"

  # 动作名称验证
  action_name_pattern: "^[a-z_:]+$"

# 缓存配置
cache:
  # 用户权限缓存时间（秒）
  user_permissions_ttl: 3600

  # 角色权限缓存时间（秒）
  role_permissions_ttl: 7200

  # 菜单缓存时间（秒）
  menu_cache_ttl: 1800
